name: 'Build Size Diff'
description: 'Automated bundle size scanning (baseline)'
author: 'Giorgi Kishmareia'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  build-command:
    description: 'Build command to run'
    required: false
    default: 'npm run build'
  build-timeout-minutes:
    description: 'Max minutes to allow build to run before failing'
    required: false
    default: '15'
  allow-unsafe-build:
    description: 'Allow build execution that requires a shell'
    required: false
    default: 'false'
  fail-on-stderr:
    description: 'Fail build if stderr output is non-empty'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for artifact access'
    required: true
  dist-path:
    description: 'Output directory to scan'
    required: false
    default: 'dist'
  gzip:
    description: 'Calculate gzip sizes'
    required: false
    default: 'true'
  brotli:
    description: 'Calculate brotli sizes'
    required: false
    default: 'true'
  budget-max-increase-kb:
    description: 'Maximum allowed size increase in KB (e.g., 10 or 0.5)'
    required: false
  warn-above-kb:
    description: 'Warn if any file grows more than this KB (e.g., 50)'
    required: false
  fail-above-kb:
    description: 'Fail if any file grows more than this KB (e.g., 100)'
    required: false
  comment-mode:
    description: 'When to comment: always, on-increase, never'
    required: false
    default: 'always'
  fail-on-comment-error:
    description: 'Fail workflow if PR comment cannot be posted'
    required: false
    default: 'false'

outputs:
  total-size:
    description: 'Total bundle size in bytes'
  total-gzip:
    description: 'Total gzip size in bytes'
  total-brotli:
    description: 'Total brotli size in bytes'
  diff-size:
    description: 'Size difference in bytes'
  diff-gzip:
    description: 'Gzip size difference in bytes'
  diff-brotli:
    description: 'Brotli size difference in bytes'
  status:
    description: 'Status: pass, fail, no-baseline, or baseline-updated'

runs:
  using: 'node20'
  main: 'dist/index.cjs'
